name: tezster_dart_web
description: A flutter package which provides the functionalities to play around
  with tezos dApps
version: 2.1.2-beta.2
homepage: https://github.com/Tezsure/tezster_dart
repository: https://github.com/Tezsure/tezster_dart
issue_tracker: https://github.com/Tezsure/tezster_dart/issues

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bip39: ^1.0.3
  blake2b: ^0.1.2
  bs58check: ^1.0.1
  convert: ^2.1.1
  crypto: ^2.1.5
  sodium_web: ^0.0.5
  http: ^0.13.3
  password_hash: ^2.0.0
  unorm_dart: ^0.1.2
  ed25519_hd_key: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
